
theme: jekyll-theme-dinky

url: "https://SinesioBittencourt.github.io"

baseurl: https://SinesioBittencourt.github.io

google-tracking-id: ""

force-https: True

#############
# HTML Head #
#############

lang: "pt-br"
author: "Sinesio Bittencourt - contato@sinesio.com.br "
title: "{ SnappyDroid }"
description: "SnappyDroid é um projeto OpenSouce feito com Arduino"
keywords: ""
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

###########
# Contact #
###########

email: "contato@snappydroid.com.br"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################




