
theme: jekyll-theme-dinky

# Site settings

# NB! Set your site's url, otherwise stuff will break :) 

url: "https://SinesioBittencourt.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: https://SinesioBittencourt.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-102624626-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "pt-br"
author: "Sinesio Bittencourt - contato@sinesio.com.br "
title: "{ SnappyDroid }"
description: "SnappyDroid é um projeto OpenSouce feito com Arduino"
keywords: ""
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"



###########
# Contact #
###########

email: "contato@snappydroid.com.br"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################




