
theme: jekyll-theme-dinky

###########
# Contact #
###########

email: "contato@snappydroid.com.br"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################




